ALTER TABLE public.access_grants ADD CONSTRAINT access_grants_auth_kind_check CHECK ((auth_kind = ANY (ARRAY['jwt_exchange'::text, 'rpc_token'::text, 'password'::text])));
ALTER TABLE public.access_grants ADD CONSTRAINT access_grants_password_shape_check CHECK (((auth_kind <> 'password'::text) OR ((email IS NOT NULL) AND (token_hash IS NULL))));
ALTER TABLE public.access_grants ADD CONSTRAINT access_grants_pkey PRIMARY KEY (id);
ALTER TABLE public.access_grants ADD CONSTRAINT access_grants_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'viewer'::text, 'checkin'::text, 'staff'::text, 'facilitator'::text, 'mentor'::text, 'juror'::text])));
ALTER TABLE public.access_grants ADD CONSTRAINT access_grants_token_hash_key UNIQUE (token_hash);
ALTER TABLE public.announcements ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);
ALTER TABLE public.app_settings ADD CONSTRAINT app_settings_pkey PRIMARY KEY (key);
ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_actor_type_check CHECK ((actor_type = ANY (ARRAY['public'::text, 'admin'::text, 'system'::text])));
ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.bulk_orders ADD CONSTRAINT bulk_orders_payment_status_check CHECK ((payment_status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text])));
ALTER TABLE public.bulk_orders ADD CONSTRAINT bulk_orders_pkey PRIMARY KEY (id);
ALTER TABLE public.bulk_orders ADD CONSTRAINT bulk_orders_ticket_price_check CHECK ((ticket_price > 0));
ALTER TABLE public.bulk_orders ADD CONSTRAINT bulk_orders_ticket_tier_check CHECK ((ticket_tier = ANY (ARRAY['early_bird'::text, 'regular'::text, 'dati'::text, 'corporate'::text])));
ALTER TABLE public.bulk_orders ADD CONSTRAINT bulk_orders_total_tickets_check CHECK (((total_tickets > 0) AND (total_tickets <= 100)));
ALTER TABLE public.bulk_vouchers ADD CONSTRAINT bulk_vouchers_code_key UNIQUE (code);
ALTER TABLE public.bulk_vouchers ADD CONSTRAINT bulk_vouchers_pkey PRIMARY KEY (id);
ALTER TABLE public.bulk_vouchers ADD CONSTRAINT bulk_vouchers_status_check CHECK ((status = ANY (ARRAY['active'::text, 'redeemed'::text, 'cancelled'::text])));
ALTER TABLE public.event_evaluations ADD CONSTRAINT event_evaluations_pkey PRIMARY KEY (id);
ALTER TABLE public.event_evaluations ADD CONSTRAINT event_evaluations_respondent_type_check CHECK ((respondent_type = ANY (ARRAY['participant'::text, 'mentor'::text])));
ALTER TABLE public.event_evaluations ADD CONSTRAINT event_evaluations_respondent_type_respondent_id_key UNIQUE (respondent_type, respondent_id);
ALTER TABLE public.jurors ADD CONSTRAINT jurors_access_token_key UNIQUE (access_token);
ALTER TABLE public.jurors ADD CONSTRAINT jurors_pkey PRIMARY KEY (id);
ALTER TABLE public.mentor_notes ADD CONSTRAINT mentor_notes_phase_check CHECK ((phase = ANY (ARRAY['ignicao'::text, 'construcao'::text, 'apresentacao'::text])));
ALTER TABLE public.mentor_notes ADD CONSTRAINT mentor_notes_pkey PRIMARY KEY (id);
ALTER TABLE public.mentor_sessions ADD CONSTRAINT mentor_sessions_pkey PRIMARY KEY (token);
ALTER TABLE public.mentor_teams ADD CONSTRAINT mentor_teams_pkey PRIMARY KEY (mentor_id, team_id);
ALTER TABLE public.mentors ADD CONSTRAINT mentors_access_token_key UNIQUE (access_token);
ALTER TABLE public.mentors ADD CONSTRAINT mentors_email_key UNIQUE (email);
ALTER TABLE public.mentors ADD CONSTRAINT mentors_pkey PRIMARY KEY (id);
ALTER TABLE public.mp_payments ADD CONSTRAINT mp_payments_payment_id_key UNIQUE (payment_id);
ALTER TABLE public.mp_payments ADD CONSTRAINT mp_payments_pkey PRIMARY KEY (id);
ALTER TABLE public.mp_sync_status ADD CONSTRAINT mp_sync_status_id_check CHECK ((id = 1));
ALTER TABLE public.mp_sync_status ADD CONSTRAINT mp_sync_status_pkey PRIMARY KEY (id);
ALTER TABLE public.notification_recipients ADD CONSTRAINT notification_recipients_pkey PRIMARY KEY (id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.pain_votes ADD CONSTRAINT pain_votes_pain_id_registration_id_key UNIQUE (pain_id, registration_id);
ALTER TABLE public.pain_votes ADD CONSTRAINT pain_votes_pkey PRIMARY KEY (id);
ALTER TABLE public.pains ADD CONSTRAINT pains_pkey PRIMARY KEY (id);
ALTER TABLE public.pains ADD CONSTRAINT pains_status_check CHECK ((status = ANY (ARRAY['visible'::text, 'hidden'::text])));
ALTER TABLE public.participant_sessions ADD CONSTRAINT participant_sessions_pkey PRIMARY KEY (token);
ALTER TABLE public.pre_pitch_evaluations ADD CONSTRAINT pre_pitch_evaluations_pkey PRIMARY KEY (id);
ALTER TABLE public.pre_pitch_evaluations ADD CONSTRAINT pre_pitch_evaluations_round_check CHECK ((round = ANY (ARRAY[1, 2])));
ALTER TABLE public.pre_pitch_evaluations ADD CONSTRAINT uq_prepitch_mentor_team_round UNIQUE (mentor_id, team_id, round);
ALTER TABLE public.prepitch_room_mentors ADD CONSTRAINT prepitch_room_mentors_pkey PRIMARY KEY (room_id, mentor_id);
ALTER TABLE public.prepitch_room_teams ADD CONSTRAINT prepitch_room_teams_pkey PRIMARY KEY (room_id, team_id);
ALTER TABLE public.prepitch_rooms ADD CONSTRAINT prepitch_rooms_pkey PRIMARY KEY (id);
ALTER TABLE public.prepitch_rooms ADD CONSTRAINT prepitch_rooms_round_check CHECK ((round = ANY (ARRAY[1, 2])));
ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_endpoint_key UNIQUE (endpoint);
ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.rate_limits ADD CONSTRAINT rate_limits_pkey PRIMARY KEY (key);
ALTER TABLE public.registrations ADD CONSTRAINT chk_ticket_price CHECK ((((ticket_tier = 'corporate'::text) AND (ticket_price > 0)) OR ((ticket_tier <> 'corporate'::text) AND (ticket_price = ANY (ARRAY[15000, 16000, 20000])))));
ALTER TABLE public.registrations ADD CONSTRAINT registrations_ai_experience_level_check CHECK (((ai_experience_level >= 1) AND (ai_experience_level <= 10)));
ALTER TABLE public.registrations ADD CONSTRAINT registrations_inscription_modality_check CHECK ((inscription_modality = ANY (ARRAY['individual_form_team'::text, 'individual_own'::text, 'team'::text])));
ALTER TABLE public.registrations ADD CONSTRAINT registrations_occupation_type_check CHECK ((occupation_type = ANY (ARRAY['hacker'::text, 'hustler'::text, 'hipster'::text, 'enthusiast'::text])));
ALTER TABLE public.registrations ADD CONSTRAINT registrations_payment_method_check CHECK ((payment_method = ANY (ARRAY['pix'::text, 'card'::text])));
ALTER TABLE public.registrations ADD CONSTRAINT registrations_payment_status_check CHECK ((payment_status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text])));
ALTER TABLE public.registrations ADD CONSTRAINT registrations_pkey PRIMARY KEY (id);
ALTER TABLE public.registrations ADD CONSTRAINT registrations_ticket_tier_check CHECK ((ticket_tier = ANY (ARRAY['early_bird'::text, 'regular'::text, 'dati'::text, 'corporate'::text])));
ALTER TABLE public.resources ADD CONSTRAINT resources_file_xor_link CHECK (((file_path IS NOT NULL) <> (url IS NOT NULL)));
ALTER TABLE public.resources ADD CONSTRAINT resources_pkey PRIMARY KEY (id);
ALTER TABLE public.schedule_days ADD CONSTRAINT schedule_days_pkey PRIMARY KEY (day_key);
ALTER TABLE public.schedule_items ADD CONSTRAINT schedule_items_pkey PRIMARY KEY (id);
ALTER TABLE public.slides_config ADD CONSTRAINT slides_config_id_check CHECK (id);
ALTER TABLE public.slides_config ADD CONSTRAINT slides_config_pkey PRIMARY KEY (id);
ALTER TABLE public.sugar_cubes ADD CONSTRAINT sugar_cubes_pkey PRIMARY KEY (id);
ALTER TABLE public.sugar_cubes ADD CONSTRAINT sugar_cubes_recipient_type_check CHECK ((recipient_type = ANY (ARRAY['participant'::text, 'mentor'::text, 'organization'::text])));
ALTER TABLE public.sugar_cubes ADD CONSTRAINT sugar_cubes_sender_type_check CHECK ((sender_type = ANY (ARRAY['participant'::text, 'mentor'::text, 'organization'::text])));
ALTER TABLE public.sugar_cubes ADD CONSTRAINT sugar_cubes_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])));
ALTER TABLE public.team_deliverable_meta ADD CONSTRAINT team_deliverable_meta_pkey PRIMARY KEY (team_id, field);
ALTER TABLE public.team_evaluations ADD CONSTRAINT team_evaluations_deliverable_check CHECK ((deliverable = ANY (ARRAY['fase1'::text, 'fase2'::text, 'fase3'::text])));
ALTER TABLE public.team_evaluations ADD CONSTRAINT team_evaluations_evaluator_type_check CHECK ((evaluator_type = ANY (ARRAY['ai'::text, 'human'::text])));
ALTER TABLE public.team_evaluations ADD CONSTRAINT team_evaluations_pkey PRIMARY KEY (id);
ALTER TABLE public.team_evaluations ADD CONSTRAINT team_evaluations_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'done'::text, 'error'::text])));
ALTER TABLE public.team_join_requests ADD CONSTRAINT team_join_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.team_join_requests ADD CONSTRAINT team_join_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text])));
ALTER TABLE public.teams ADD CONSTRAINT teams_pkey PRIMARY KEY (id);
ALTER TABLE public.teams ADD CONSTRAINT teams_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'submitted'::text, 'reviewing'::text, 'evaluated'::text])));
ALTER TABLE public.waitlist ADD CONSTRAINT waitlist_email_key UNIQUE (email);
ALTER TABLE public.waitlist ADD CONSTRAINT waitlist_pkey PRIMARY KEY (id);
ALTER TABLE public.wall_state ADD CONSTRAINT wall_state_id_check CHECK ((id = true));
ALTER TABLE public.wall_state ADD CONSTRAINT wall_state_phase_check CHECK ((phase = ANY (ARRAY['closed'::text, 'wall_open'::text, 'voting_open'::text, 'results'::text])));
ALTER TABLE public.wall_state ADD CONSTRAINT wall_state_pkey PRIMARY KEY (id);
ALTER TABLE public.bulk_vouchers ADD CONSTRAINT bulk_vouchers_bulk_order_id_fkey FOREIGN KEY (bulk_order_id) REFERENCES bulk_orders(id) ON DELETE CASCADE;
ALTER TABLE public.bulk_vouchers ADD CONSTRAINT bulk_vouchers_redeemed_by_id_fkey FOREIGN KEY (redeemed_by_id) REFERENCES registrations(id);
ALTER TABLE public.mentor_notes ADD CONSTRAINT mentor_notes_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES mentors(id) ON DELETE CASCADE;
ALTER TABLE public.mentor_notes ADD CONSTRAINT mentor_notes_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.mentor_sessions ADD CONSTRAINT mentor_sessions_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES mentors(id) ON DELETE CASCADE;
ALTER TABLE public.mentor_teams ADD CONSTRAINT mentor_teams_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES mentors(id) ON DELETE CASCADE;
ALTER TABLE public.mentor_teams ADD CONSTRAINT mentor_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.mp_payments ADD CONSTRAINT mp_payments_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES registrations(id);
ALTER TABLE public.notification_recipients ADD CONSTRAINT notification_recipients_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE CASCADE;
ALTER TABLE public.pain_votes ADD CONSTRAINT pain_votes_pain_id_fkey FOREIGN KEY (pain_id) REFERENCES pains(id) ON DELETE CASCADE;
ALTER TABLE public.pain_votes ADD CONSTRAINT pain_votes_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE CASCADE;
ALTER TABLE public.pains ADD CONSTRAINT pains_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE CASCADE;
ALTER TABLE public.participant_sessions ADD CONSTRAINT participant_sessions_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES registrations(id) ON DELETE CASCADE;
ALTER TABLE public.pre_pitch_evaluations ADD CONSTRAINT pre_pitch_evaluations_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES mentors(id) ON DELETE CASCADE;
ALTER TABLE public.pre_pitch_evaluations ADD CONSTRAINT pre_pitch_evaluations_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.prepitch_room_mentors ADD CONSTRAINT prepitch_room_mentors_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES mentors(id) ON DELETE CASCADE;
ALTER TABLE public.prepitch_room_mentors ADD CONSTRAINT prepitch_room_mentors_room_id_fkey FOREIGN KEY (room_id) REFERENCES prepitch_rooms(id) ON DELETE CASCADE;
ALTER TABLE public.prepitch_room_teams ADD CONSTRAINT prepitch_room_teams_room_id_fkey FOREIGN KEY (room_id) REFERENCES prepitch_rooms(id) ON DELETE CASCADE;
ALTER TABLE public.prepitch_room_teams ADD CONSTRAINT prepitch_room_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.registrations ADD CONSTRAINT registrations_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.registrations ADD CONSTRAINT registrations_transferred_from_id_fkey FOREIGN KEY (transferred_from_id) REFERENCES registrations(id);
ALTER TABLE public.registrations ADD CONSTRAINT registrations_transferred_to_id_fkey FOREIGN KEY (transferred_to_id) REFERENCES registrations(id);
ALTER TABLE public.schedule_items ADD CONSTRAINT schedule_items_day_key_fkey FOREIGN KEY (day_key) REFERENCES schedule_days(day_key) ON DELETE CASCADE;
ALTER TABLE public.team_deliverable_meta ADD CONSTRAINT team_deliverable_meta_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.team_evaluations ADD CONSTRAINT team_evaluations_juror_id_fkey FOREIGN KEY (juror_id) REFERENCES jurors(id) ON DELETE CASCADE;
ALTER TABLE public.team_evaluations ADD CONSTRAINT team_evaluations_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.team_join_requests ADD CONSTRAINT team_join_requests_decided_by_id_fkey FOREIGN KEY (decided_by_id) REFERENCES registrations(id);
ALTER TABLE public.team_join_requests ADD CONSTRAINT team_join_requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES registrations(id) ON DELETE CASCADE;
ALTER TABLE public.teams ADD CONSTRAINT teams_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES registrations(id);
