CREATE INDEX IF NOT EXISTS idx_access_grants_role ON public.access_grants USING btree (role);
CREATE INDEX IF NOT EXISTS idx_access_grants_token_hash ON public.access_grants USING btree (token_hash);
CREATE INDEX IF NOT EXISTS announcements_active_idx ON public.announcements USING btree (active, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_action ON public.audit_log USING btree (action);
CREATE INDEX IF NOT EXISTS idx_audit_created_at ON public.audit_log USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_target_id ON public.audit_log USING btree (target_id);
CREATE INDEX IF NOT EXISTS idx_bulk_orders_email ON public.bulk_orders USING btree (lower(contact_email));
CREATE INDEX IF NOT EXISTS idx_bulk_orders_status ON public.bulk_orders USING btree (payment_status);
CREATE INDEX IF NOT EXISTS idx_bulk_vouchers_order ON public.bulk_vouchers USING btree (bulk_order_id);
CREATE INDEX IF NOT EXISTS idx_bulk_vouchers_redeemed ON public.bulk_vouchers USING btree (redeemed_by_id);
CREATE INDEX IF NOT EXISTS idx_bulk_vouchers_status ON public.bulk_vouchers USING btree (status);
CREATE INDEX IF NOT EXISTS idx_mentor_notes_team ON public.mentor_notes USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_mentor_sessions_mentor ON public.mentor_sessions USING btree (mentor_id);
CREATE INDEX IF NOT EXISTS idx_mentor_teams_mentor ON public.mentor_teams USING btree (mentor_id);
CREATE INDEX IF NOT EXISTS idx_mentor_teams_team ON public.mentor_teams USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_mp_payments_operation_type ON public.mp_payments USING btree (operation_type);
CREATE INDEX IF NOT EXISTS idx_mp_payments_registration_id ON public.mp_payments USING btree (registration_id);
CREATE INDEX IF NOT EXISTS idx_mp_payments_status ON public.mp_payments USING btree (status);
CREATE INDEX IF NOT EXISTS idx_notif_recip_notif ON public.notification_recipients USING btree (notification_id);
CREATE INDEX IF NOT EXISTS idx_notif_recip_user ON public.notification_recipients USING btree (user_key, read_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_notif_recip ON public.notification_recipients USING btree (notification_id, user_key);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pain_votes_pain ON public.pain_votes USING btree (pain_id);
CREATE INDEX IF NOT EXISTS idx_pain_votes_registration ON public.pain_votes USING btree (registration_id);
CREATE INDEX IF NOT EXISTS idx_pains_registration ON public.pains USING btree (registration_id);
CREATE INDEX IF NOT EXISTS idx_pains_status ON public.pains USING btree (status);
CREATE INDEX IF NOT EXISTS idx_participant_sessions_expires ON public.participant_sessions USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_participant_sessions_reg ON public.participant_sessions USING btree (registration_id);
CREATE INDEX IF NOT EXISTS idx_prepitch_mentor ON public.pre_pitch_evaluations USING btree (mentor_id);
CREATE INDEX IF NOT EXISTS idx_prepitch_team ON public.pre_pitch_evaluations USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_prepitch_room_mentors_mentor ON public.prepitch_room_mentors USING btree (mentor_id);
CREATE INDEX IF NOT EXISTS idx_prepitch_room_mentors_room ON public.prepitch_room_mentors USING btree (room_id);
CREATE INDEX IF NOT EXISTS idx_prepitch_room_teams_room ON public.prepitch_room_teams USING btree (room_id);
CREATE INDEX IF NOT EXISTS idx_prepitch_room_teams_team ON public.prepitch_room_teams USING btree (team_id);
CREATE INDEX IF NOT EXISTS idx_prepitch_rooms_round ON public.prepitch_rooms USING btree (round);
CREATE INDEX IF NOT EXISTS idx_push_sub_user_key ON public.push_subscriptions USING btree (user_key);
CREATE INDEX IF NOT EXISTS idx_reg_payment_status ON public.registrations USING btree (payment_status);
CREATE INDEX IF NOT EXISTS idx_reg_transferred_from ON public.registrations USING btree (transferred_from_id);
CREATE INDEX IF NOT EXISTS idx_reg_transferred_to ON public.registrations USING btree (transferred_to_id);
CREATE INDEX IF NOT EXISTS idx_registrations_team_id ON public.registrations USING btree (team_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_registrations_email_active ON public.registrations USING btree (lower(email)) WHERE (payment_status <> 'cancelled'::text);
CREATE INDEX IF NOT EXISTS schedule_items_day_idx ON public.schedule_items USING btree (day_key, sort_order);
CREATE INDEX IF NOT EXISTS idx_sugar_cubes_recipient ON public.sugar_cubes USING btree (recipient_type, recipient_ref);
CREATE INDEX IF NOT EXISTS idx_sugar_cubes_sender ON public.sugar_cubes USING btree (sender_type, sender_ref);
CREATE INDEX IF NOT EXISTS idx_sugar_cubes_status ON public.sugar_cubes USING btree (status);
CREATE INDEX IF NOT EXISTS idx_team_evaluations_team_id ON public.team_evaluations USING btree (team_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_team_eval_ai_deliverable ON public.team_evaluations USING btree (team_id, deliverable) WHERE ((evaluator_type = 'ai'::text) AND (deliverable IS NOT NULL));
CREATE UNIQUE INDEX IF NOT EXISTS uq_team_evaluations_juror_team ON public.team_evaluations USING btree (juror_id, team_id) WHERE (juror_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_team_join_requests_requester ON public.team_join_requests USING btree (requester_id);
CREATE INDEX IF NOT EXISTS idx_team_join_requests_team_pending ON public.team_join_requests USING btree (team_name) WHERE (status = 'pending'::text);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pending_join_request ON public.team_join_requests USING btree (requester_id, team_name) WHERE (status = 'pending'::text);
CREATE UNIQUE INDEX IF NOT EXISTS uq_teams_name ON public.teams USING btree (name);
