GRANT DELETE ON public.access_grants TO anon;
GRANT INSERT ON public.access_grants TO anon;
GRANT REFERENCES ON public.access_grants TO anon;
GRANT SELECT ON public.access_grants TO anon;
GRANT TRIGGER ON public.access_grants TO anon;
GRANT TRUNCATE ON public.access_grants TO anon;
GRANT UPDATE ON public.access_grants TO anon;
GRANT DELETE ON public.access_grants TO authenticated;
GRANT INSERT ON public.access_grants TO authenticated;
GRANT REFERENCES ON public.access_grants TO authenticated;
GRANT SELECT ON public.access_grants TO authenticated;
GRANT TRIGGER ON public.access_grants TO authenticated;
GRANT TRUNCATE ON public.access_grants TO authenticated;
GRANT UPDATE ON public.access_grants TO authenticated;
GRANT DELETE ON public.access_grants TO service_role;
GRANT INSERT ON public.access_grants TO service_role;
GRANT REFERENCES ON public.access_grants TO service_role;
GRANT SELECT ON public.access_grants TO service_role;
GRANT TRIGGER ON public.access_grants TO service_role;
GRANT TRUNCATE ON public.access_grants TO service_role;
GRANT UPDATE ON public.access_grants TO service_role;
GRANT DELETE ON public.announcements TO anon;
GRANT INSERT ON public.announcements TO anon;
GRANT REFERENCES ON public.announcements TO anon;
GRANT SELECT ON public.announcements TO anon;
GRANT TRIGGER ON public.announcements TO anon;
GRANT TRUNCATE ON public.announcements TO anon;
GRANT UPDATE ON public.announcements TO anon;
GRANT DELETE ON public.announcements TO authenticated;
GRANT INSERT ON public.announcements TO authenticated;
GRANT REFERENCES ON public.announcements TO authenticated;
GRANT SELECT ON public.announcements TO authenticated;
GRANT TRIGGER ON public.announcements TO authenticated;
GRANT TRUNCATE ON public.announcements TO authenticated;
GRANT UPDATE ON public.announcements TO authenticated;
GRANT DELETE ON public.announcements TO service_role;
GRANT INSERT ON public.announcements TO service_role;
GRANT REFERENCES ON public.announcements TO service_role;
GRANT SELECT ON public.announcements TO service_role;
GRANT TRIGGER ON public.announcements TO service_role;
GRANT TRUNCATE ON public.announcements TO service_role;
GRANT UPDATE ON public.announcements TO service_role;
GRANT DELETE ON public.app_settings TO anon;
GRANT INSERT ON public.app_settings TO anon;
GRANT REFERENCES ON public.app_settings TO anon;
GRANT SELECT ON public.app_settings TO anon;
GRANT TRIGGER ON public.app_settings TO anon;
GRANT TRUNCATE ON public.app_settings TO anon;
GRANT UPDATE ON public.app_settings TO anon;
GRANT DELETE ON public.app_settings TO authenticated;
GRANT INSERT ON public.app_settings TO authenticated;
GRANT REFERENCES ON public.app_settings TO authenticated;
GRANT SELECT ON public.app_settings TO authenticated;
GRANT TRIGGER ON public.app_settings TO authenticated;
GRANT TRUNCATE ON public.app_settings TO authenticated;
GRANT UPDATE ON public.app_settings TO authenticated;
GRANT DELETE ON public.app_settings TO service_role;
GRANT INSERT ON public.app_settings TO service_role;
GRANT REFERENCES ON public.app_settings TO service_role;
GRANT SELECT ON public.app_settings TO service_role;
GRANT TRIGGER ON public.app_settings TO service_role;
GRANT TRUNCATE ON public.app_settings TO service_role;
GRANT UPDATE ON public.app_settings TO service_role;
GRANT DELETE ON public.audit_log TO anon;
GRANT INSERT ON public.audit_log TO anon;
GRANT REFERENCES ON public.audit_log TO anon;
GRANT SELECT ON public.audit_log TO anon;
GRANT TRIGGER ON public.audit_log TO anon;
GRANT TRUNCATE ON public.audit_log TO anon;
GRANT UPDATE ON public.audit_log TO anon;
GRANT DELETE ON public.audit_log TO authenticated;
GRANT INSERT ON public.audit_log TO authenticated;
GRANT REFERENCES ON public.audit_log TO authenticated;
GRANT SELECT ON public.audit_log TO authenticated;
GRANT TRIGGER ON public.audit_log TO authenticated;
GRANT TRUNCATE ON public.audit_log TO authenticated;
GRANT UPDATE ON public.audit_log TO authenticated;
GRANT DELETE ON public.audit_log TO service_role;
GRANT INSERT ON public.audit_log TO service_role;
GRANT REFERENCES ON public.audit_log TO service_role;
GRANT SELECT ON public.audit_log TO service_role;
GRANT TRIGGER ON public.audit_log TO service_role;
GRANT TRUNCATE ON public.audit_log TO service_role;
GRANT UPDATE ON public.audit_log TO service_role;
GRANT DELETE ON public.bulk_orders TO anon;
GRANT INSERT ON public.bulk_orders TO anon;
GRANT REFERENCES ON public.bulk_orders TO anon;
GRANT SELECT ON public.bulk_orders TO anon;
GRANT TRIGGER ON public.bulk_orders TO anon;
GRANT TRUNCATE ON public.bulk_orders TO anon;
GRANT UPDATE ON public.bulk_orders TO anon;
GRANT DELETE ON public.bulk_orders TO authenticated;
GRANT INSERT ON public.bulk_orders TO authenticated;
GRANT REFERENCES ON public.bulk_orders TO authenticated;
GRANT SELECT ON public.bulk_orders TO authenticated;
GRANT TRIGGER ON public.bulk_orders TO authenticated;
GRANT TRUNCATE ON public.bulk_orders TO authenticated;
GRANT UPDATE ON public.bulk_orders TO authenticated;
GRANT DELETE ON public.bulk_orders TO service_role;
GRANT INSERT ON public.bulk_orders TO service_role;
GRANT REFERENCES ON public.bulk_orders TO service_role;
GRANT SELECT ON public.bulk_orders TO service_role;
GRANT TRIGGER ON public.bulk_orders TO service_role;
GRANT TRUNCATE ON public.bulk_orders TO service_role;
GRANT UPDATE ON public.bulk_orders TO service_role;
GRANT DELETE ON public.bulk_vouchers TO anon;
GRANT INSERT ON public.bulk_vouchers TO anon;
GRANT REFERENCES ON public.bulk_vouchers TO anon;
GRANT SELECT ON public.bulk_vouchers TO anon;
GRANT TRIGGER ON public.bulk_vouchers TO anon;
GRANT TRUNCATE ON public.bulk_vouchers TO anon;
GRANT UPDATE ON public.bulk_vouchers TO anon;
GRANT DELETE ON public.bulk_vouchers TO authenticated;
GRANT INSERT ON public.bulk_vouchers TO authenticated;
GRANT REFERENCES ON public.bulk_vouchers TO authenticated;
GRANT SELECT ON public.bulk_vouchers TO authenticated;
GRANT TRIGGER ON public.bulk_vouchers TO authenticated;
GRANT TRUNCATE ON public.bulk_vouchers TO authenticated;
GRANT UPDATE ON public.bulk_vouchers TO authenticated;
GRANT DELETE ON public.bulk_vouchers TO service_role;
GRANT INSERT ON public.bulk_vouchers TO service_role;
GRANT REFERENCES ON public.bulk_vouchers TO service_role;
GRANT SELECT ON public.bulk_vouchers TO service_role;
GRANT TRIGGER ON public.bulk_vouchers TO service_role;
GRANT TRUNCATE ON public.bulk_vouchers TO service_role;
GRANT UPDATE ON public.bulk_vouchers TO service_role;
GRANT DELETE ON public.event_evaluations TO anon;
GRANT INSERT ON public.event_evaluations TO anon;
GRANT REFERENCES ON public.event_evaluations TO anon;
GRANT SELECT ON public.event_evaluations TO anon;
GRANT TRIGGER ON public.event_evaluations TO anon;
GRANT TRUNCATE ON public.event_evaluations TO anon;
GRANT UPDATE ON public.event_evaluations TO anon;
GRANT DELETE ON public.event_evaluations TO authenticated;
GRANT INSERT ON public.event_evaluations TO authenticated;
GRANT REFERENCES ON public.event_evaluations TO authenticated;
GRANT SELECT ON public.event_evaluations TO authenticated;
GRANT TRIGGER ON public.event_evaluations TO authenticated;
GRANT TRUNCATE ON public.event_evaluations TO authenticated;
GRANT UPDATE ON public.event_evaluations TO authenticated;
GRANT DELETE ON public.event_evaluations TO service_role;
GRANT INSERT ON public.event_evaluations TO service_role;
GRANT REFERENCES ON public.event_evaluations TO service_role;
GRANT SELECT ON public.event_evaluations TO service_role;
GRANT TRIGGER ON public.event_evaluations TO service_role;
GRANT TRUNCATE ON public.event_evaluations TO service_role;
GRANT UPDATE ON public.event_evaluations TO service_role;
GRANT DELETE ON public.jurors TO anon;
GRANT INSERT ON public.jurors TO anon;
GRANT REFERENCES ON public.jurors TO anon;
GRANT SELECT ON public.jurors TO anon;
GRANT TRIGGER ON public.jurors TO anon;
GRANT TRUNCATE ON public.jurors TO anon;
GRANT UPDATE ON public.jurors TO anon;
GRANT DELETE ON public.jurors TO authenticated;
GRANT INSERT ON public.jurors TO authenticated;
GRANT REFERENCES ON public.jurors TO authenticated;
GRANT SELECT ON public.jurors TO authenticated;
GRANT TRIGGER ON public.jurors TO authenticated;
GRANT TRUNCATE ON public.jurors TO authenticated;
GRANT UPDATE ON public.jurors TO authenticated;
GRANT DELETE ON public.jurors TO service_role;
GRANT INSERT ON public.jurors TO service_role;
GRANT REFERENCES ON public.jurors TO service_role;
GRANT SELECT ON public.jurors TO service_role;
GRANT TRIGGER ON public.jurors TO service_role;
GRANT TRUNCATE ON public.jurors TO service_role;
GRANT UPDATE ON public.jurors TO service_role;
GRANT DELETE ON public.mentor_notes TO anon;
GRANT INSERT ON public.mentor_notes TO anon;
GRANT REFERENCES ON public.mentor_notes TO anon;
GRANT SELECT ON public.mentor_notes TO anon;
GRANT TRIGGER ON public.mentor_notes TO anon;
GRANT TRUNCATE ON public.mentor_notes TO anon;
GRANT UPDATE ON public.mentor_notes TO anon;
GRANT DELETE ON public.mentor_notes TO authenticated;
GRANT INSERT ON public.mentor_notes TO authenticated;
GRANT REFERENCES ON public.mentor_notes TO authenticated;
GRANT SELECT ON public.mentor_notes TO authenticated;
GRANT TRIGGER ON public.mentor_notes TO authenticated;
GRANT TRUNCATE ON public.mentor_notes TO authenticated;
GRANT UPDATE ON public.mentor_notes TO authenticated;
GRANT DELETE ON public.mentor_notes TO service_role;
GRANT INSERT ON public.mentor_notes TO service_role;
GRANT REFERENCES ON public.mentor_notes TO service_role;
GRANT SELECT ON public.mentor_notes TO service_role;
GRANT TRIGGER ON public.mentor_notes TO service_role;
GRANT TRUNCATE ON public.mentor_notes TO service_role;
GRANT UPDATE ON public.mentor_notes TO service_role;
GRANT DELETE ON public.mentor_sessions TO anon;
GRANT INSERT ON public.mentor_sessions TO anon;
GRANT REFERENCES ON public.mentor_sessions TO anon;
GRANT SELECT ON public.mentor_sessions TO anon;
GRANT TRIGGER ON public.mentor_sessions TO anon;
GRANT TRUNCATE ON public.mentor_sessions TO anon;
GRANT UPDATE ON public.mentor_sessions TO anon;
GRANT DELETE ON public.mentor_sessions TO authenticated;
GRANT INSERT ON public.mentor_sessions TO authenticated;
GRANT REFERENCES ON public.mentor_sessions TO authenticated;
GRANT SELECT ON public.mentor_sessions TO authenticated;
GRANT TRIGGER ON public.mentor_sessions TO authenticated;
GRANT TRUNCATE ON public.mentor_sessions TO authenticated;
GRANT UPDATE ON public.mentor_sessions TO authenticated;
GRANT DELETE ON public.mentor_sessions TO service_role;
GRANT INSERT ON public.mentor_sessions TO service_role;
GRANT REFERENCES ON public.mentor_sessions TO service_role;
GRANT SELECT ON public.mentor_sessions TO service_role;
GRANT TRIGGER ON public.mentor_sessions TO service_role;
GRANT TRUNCATE ON public.mentor_sessions TO service_role;
GRANT UPDATE ON public.mentor_sessions TO service_role;
GRANT DELETE ON public.mentor_teams TO anon;
GRANT INSERT ON public.mentor_teams TO anon;
GRANT REFERENCES ON public.mentor_teams TO anon;
GRANT SELECT ON public.mentor_teams TO anon;
GRANT TRIGGER ON public.mentor_teams TO anon;
GRANT TRUNCATE ON public.mentor_teams TO anon;
GRANT UPDATE ON public.mentor_teams TO anon;
GRANT DELETE ON public.mentor_teams TO authenticated;
GRANT INSERT ON public.mentor_teams TO authenticated;
GRANT REFERENCES ON public.mentor_teams TO authenticated;
GRANT SELECT ON public.mentor_teams TO authenticated;
GRANT TRIGGER ON public.mentor_teams TO authenticated;
GRANT TRUNCATE ON public.mentor_teams TO authenticated;
GRANT UPDATE ON public.mentor_teams TO authenticated;
GRANT DELETE ON public.mentor_teams TO service_role;
GRANT INSERT ON public.mentor_teams TO service_role;
GRANT REFERENCES ON public.mentor_teams TO service_role;
GRANT SELECT ON public.mentor_teams TO service_role;
GRANT TRIGGER ON public.mentor_teams TO service_role;
GRANT TRUNCATE ON public.mentor_teams TO service_role;
GRANT UPDATE ON public.mentor_teams TO service_role;
GRANT DELETE ON public.mentors TO anon;
GRANT INSERT ON public.mentors TO anon;
GRANT REFERENCES ON public.mentors TO anon;
GRANT TRIGGER ON public.mentors TO anon;
GRANT TRUNCATE ON public.mentors TO anon;
GRANT UPDATE ON public.mentors TO anon;
GRANT DELETE ON public.mentors TO authenticated;
GRANT INSERT ON public.mentors TO authenticated;
GRANT REFERENCES ON public.mentors TO authenticated;
GRANT TRIGGER ON public.mentors TO authenticated;
GRANT TRUNCATE ON public.mentors TO authenticated;
GRANT UPDATE ON public.mentors TO authenticated;
GRANT DELETE ON public.mentors TO service_role;
GRANT INSERT ON public.mentors TO service_role;
GRANT REFERENCES ON public.mentors TO service_role;
GRANT SELECT ON public.mentors TO service_role;
GRANT TRIGGER ON public.mentors TO service_role;
GRANT TRUNCATE ON public.mentors TO service_role;
GRANT UPDATE ON public.mentors TO service_role;
GRANT DELETE ON public.mp_payments TO anon;
GRANT INSERT ON public.mp_payments TO anon;
GRANT REFERENCES ON public.mp_payments TO anon;
GRANT SELECT ON public.mp_payments TO anon;
GRANT TRIGGER ON public.mp_payments TO anon;
GRANT TRUNCATE ON public.mp_payments TO anon;
GRANT UPDATE ON public.mp_payments TO anon;
GRANT DELETE ON public.mp_payments TO authenticated;
GRANT INSERT ON public.mp_payments TO authenticated;
GRANT REFERENCES ON public.mp_payments TO authenticated;
GRANT SELECT ON public.mp_payments TO authenticated;
GRANT TRIGGER ON public.mp_payments TO authenticated;
GRANT TRUNCATE ON public.mp_payments TO authenticated;
GRANT UPDATE ON public.mp_payments TO authenticated;
GRANT DELETE ON public.mp_payments TO service_role;
GRANT INSERT ON public.mp_payments TO service_role;
GRANT REFERENCES ON public.mp_payments TO service_role;
GRANT SELECT ON public.mp_payments TO service_role;
GRANT TRIGGER ON public.mp_payments TO service_role;
GRANT TRUNCATE ON public.mp_payments TO service_role;
GRANT UPDATE ON public.mp_payments TO service_role;
GRANT DELETE ON public.mp_sync_status TO anon;
GRANT INSERT ON public.mp_sync_status TO anon;
GRANT REFERENCES ON public.mp_sync_status TO anon;
GRANT SELECT ON public.mp_sync_status TO anon;
GRANT TRIGGER ON public.mp_sync_status TO anon;
GRANT TRUNCATE ON public.mp_sync_status TO anon;
GRANT UPDATE ON public.mp_sync_status TO anon;
GRANT DELETE ON public.mp_sync_status TO authenticated;
GRANT INSERT ON public.mp_sync_status TO authenticated;
GRANT REFERENCES ON public.mp_sync_status TO authenticated;
GRANT SELECT ON public.mp_sync_status TO authenticated;
GRANT TRIGGER ON public.mp_sync_status TO authenticated;
GRANT TRUNCATE ON public.mp_sync_status TO authenticated;
GRANT UPDATE ON public.mp_sync_status TO authenticated;
GRANT DELETE ON public.mp_sync_status TO service_role;
GRANT INSERT ON public.mp_sync_status TO service_role;
GRANT REFERENCES ON public.mp_sync_status TO service_role;
GRANT SELECT ON public.mp_sync_status TO service_role;
GRANT TRIGGER ON public.mp_sync_status TO service_role;
GRANT TRUNCATE ON public.mp_sync_status TO service_role;
GRANT UPDATE ON public.mp_sync_status TO service_role;
GRANT DELETE ON public.notification_recipients TO anon;
GRANT INSERT ON public.notification_recipients TO anon;
GRANT REFERENCES ON public.notification_recipients TO anon;
GRANT SELECT ON public.notification_recipients TO anon;
GRANT TRIGGER ON public.notification_recipients TO anon;
GRANT TRUNCATE ON public.notification_recipients TO anon;
GRANT UPDATE ON public.notification_recipients TO anon;
GRANT DELETE ON public.notification_recipients TO authenticated;
GRANT INSERT ON public.notification_recipients TO authenticated;
GRANT REFERENCES ON public.notification_recipients TO authenticated;
GRANT SELECT ON public.notification_recipients TO authenticated;
GRANT TRIGGER ON public.notification_recipients TO authenticated;
GRANT TRUNCATE ON public.notification_recipients TO authenticated;
GRANT UPDATE ON public.notification_recipients TO authenticated;
GRANT DELETE ON public.notification_recipients TO service_role;
GRANT INSERT ON public.notification_recipients TO service_role;
GRANT REFERENCES ON public.notification_recipients TO service_role;
GRANT SELECT ON public.notification_recipients TO service_role;
GRANT TRIGGER ON public.notification_recipients TO service_role;
GRANT TRUNCATE ON public.notification_recipients TO service_role;
GRANT UPDATE ON public.notification_recipients TO service_role;
GRANT DELETE ON public.notifications TO anon;
GRANT INSERT ON public.notifications TO anon;
GRANT REFERENCES ON public.notifications TO anon;
GRANT SELECT ON public.notifications TO anon;
GRANT TRIGGER ON public.notifications TO anon;
GRANT TRUNCATE ON public.notifications TO anon;
GRANT UPDATE ON public.notifications TO anon;
GRANT DELETE ON public.notifications TO authenticated;
GRANT INSERT ON public.notifications TO authenticated;
GRANT REFERENCES ON public.notifications TO authenticated;
GRANT SELECT ON public.notifications TO authenticated;
GRANT TRIGGER ON public.notifications TO authenticated;
GRANT TRUNCATE ON public.notifications TO authenticated;
GRANT UPDATE ON public.notifications TO authenticated;
GRANT DELETE ON public.notifications TO service_role;
GRANT INSERT ON public.notifications TO service_role;
GRANT REFERENCES ON public.notifications TO service_role;
GRANT SELECT ON public.notifications TO service_role;
GRANT TRIGGER ON public.notifications TO service_role;
GRANT TRUNCATE ON public.notifications TO service_role;
GRANT UPDATE ON public.notifications TO service_role;
GRANT DELETE ON public.pain_votes TO anon;
GRANT INSERT ON public.pain_votes TO anon;
GRANT REFERENCES ON public.pain_votes TO anon;
GRANT SELECT ON public.pain_votes TO anon;
GRANT TRIGGER ON public.pain_votes TO anon;
GRANT TRUNCATE ON public.pain_votes TO anon;
GRANT UPDATE ON public.pain_votes TO anon;
GRANT DELETE ON public.pain_votes TO authenticated;
GRANT INSERT ON public.pain_votes TO authenticated;
GRANT REFERENCES ON public.pain_votes TO authenticated;
GRANT SELECT ON public.pain_votes TO authenticated;
GRANT TRIGGER ON public.pain_votes TO authenticated;
GRANT TRUNCATE ON public.pain_votes TO authenticated;
GRANT UPDATE ON public.pain_votes TO authenticated;
GRANT DELETE ON public.pain_votes TO service_role;
GRANT INSERT ON public.pain_votes TO service_role;
GRANT REFERENCES ON public.pain_votes TO service_role;
GRANT SELECT ON public.pain_votes TO service_role;
GRANT TRIGGER ON public.pain_votes TO service_role;
GRANT TRUNCATE ON public.pain_votes TO service_role;
GRANT UPDATE ON public.pain_votes TO service_role;
GRANT DELETE ON public.pains TO anon;
GRANT INSERT ON public.pains TO anon;
GRANT REFERENCES ON public.pains TO anon;
GRANT SELECT ON public.pains TO anon;
GRANT TRIGGER ON public.pains TO anon;
GRANT TRUNCATE ON public.pains TO anon;
GRANT UPDATE ON public.pains TO anon;
GRANT DELETE ON public.pains TO authenticated;
GRANT INSERT ON public.pains TO authenticated;
GRANT REFERENCES ON public.pains TO authenticated;
GRANT SELECT ON public.pains TO authenticated;
GRANT TRIGGER ON public.pains TO authenticated;
GRANT TRUNCATE ON public.pains TO authenticated;
GRANT UPDATE ON public.pains TO authenticated;
GRANT DELETE ON public.pains TO service_role;
GRANT INSERT ON public.pains TO service_role;
GRANT REFERENCES ON public.pains TO service_role;
GRANT SELECT ON public.pains TO service_role;
GRANT TRIGGER ON public.pains TO service_role;
GRANT TRUNCATE ON public.pains TO service_role;
GRANT UPDATE ON public.pains TO service_role;
GRANT DELETE ON public.participant_sessions TO anon;
GRANT INSERT ON public.participant_sessions TO anon;
GRANT REFERENCES ON public.participant_sessions TO anon;
GRANT SELECT ON public.participant_sessions TO anon;
GRANT TRIGGER ON public.participant_sessions TO anon;
GRANT TRUNCATE ON public.participant_sessions TO anon;
GRANT UPDATE ON public.participant_sessions TO anon;
GRANT DELETE ON public.participant_sessions TO authenticated;
GRANT INSERT ON public.participant_sessions TO authenticated;
GRANT REFERENCES ON public.participant_sessions TO authenticated;
GRANT SELECT ON public.participant_sessions TO authenticated;
GRANT TRIGGER ON public.participant_sessions TO authenticated;
GRANT TRUNCATE ON public.participant_sessions TO authenticated;
GRANT UPDATE ON public.participant_sessions TO authenticated;
GRANT DELETE ON public.participant_sessions TO service_role;
GRANT INSERT ON public.participant_sessions TO service_role;
GRANT REFERENCES ON public.participant_sessions TO service_role;
GRANT SELECT ON public.participant_sessions TO service_role;
GRANT TRIGGER ON public.participant_sessions TO service_role;
GRANT TRUNCATE ON public.participant_sessions TO service_role;
GRANT UPDATE ON public.participant_sessions TO service_role;
GRANT DELETE ON public.pre_pitch_evaluations TO anon;
GRANT INSERT ON public.pre_pitch_evaluations TO anon;
GRANT REFERENCES ON public.pre_pitch_evaluations TO anon;
GRANT SELECT ON public.pre_pitch_evaluations TO anon;
GRANT TRIGGER ON public.pre_pitch_evaluations TO anon;
GRANT TRUNCATE ON public.pre_pitch_evaluations TO anon;
GRANT UPDATE ON public.pre_pitch_evaluations TO anon;
GRANT DELETE ON public.pre_pitch_evaluations TO authenticated;
GRANT INSERT ON public.pre_pitch_evaluations TO authenticated;
GRANT REFERENCES ON public.pre_pitch_evaluations TO authenticated;
GRANT SELECT ON public.pre_pitch_evaluations TO authenticated;
GRANT TRIGGER ON public.pre_pitch_evaluations TO authenticated;
GRANT TRUNCATE ON public.pre_pitch_evaluations TO authenticated;
GRANT UPDATE ON public.pre_pitch_evaluations TO authenticated;
GRANT DELETE ON public.pre_pitch_evaluations TO service_role;
GRANT INSERT ON public.pre_pitch_evaluations TO service_role;
GRANT REFERENCES ON public.pre_pitch_evaluations TO service_role;
GRANT SELECT ON public.pre_pitch_evaluations TO service_role;
GRANT TRIGGER ON public.pre_pitch_evaluations TO service_role;
GRANT TRUNCATE ON public.pre_pitch_evaluations TO service_role;
GRANT UPDATE ON public.pre_pitch_evaluations TO service_role;
GRANT DELETE ON public.prepitch_room_mentors TO anon;
GRANT INSERT ON public.prepitch_room_mentors TO anon;
GRANT REFERENCES ON public.prepitch_room_mentors TO anon;
GRANT SELECT ON public.prepitch_room_mentors TO anon;
GRANT TRIGGER ON public.prepitch_room_mentors TO anon;
GRANT TRUNCATE ON public.prepitch_room_mentors TO anon;
GRANT UPDATE ON public.prepitch_room_mentors TO anon;
GRANT DELETE ON public.prepitch_room_mentors TO authenticated;
GRANT INSERT ON public.prepitch_room_mentors TO authenticated;
GRANT REFERENCES ON public.prepitch_room_mentors TO authenticated;
GRANT SELECT ON public.prepitch_room_mentors TO authenticated;
GRANT TRIGGER ON public.prepitch_room_mentors TO authenticated;
GRANT TRUNCATE ON public.prepitch_room_mentors TO authenticated;
GRANT UPDATE ON public.prepitch_room_mentors TO authenticated;
GRANT DELETE ON public.prepitch_room_mentors TO service_role;
GRANT INSERT ON public.prepitch_room_mentors TO service_role;
GRANT REFERENCES ON public.prepitch_room_mentors TO service_role;
GRANT SELECT ON public.prepitch_room_mentors TO service_role;
GRANT TRIGGER ON public.prepitch_room_mentors TO service_role;
GRANT TRUNCATE ON public.prepitch_room_mentors TO service_role;
GRANT UPDATE ON public.prepitch_room_mentors TO service_role;
GRANT DELETE ON public.prepitch_room_teams TO anon;
GRANT INSERT ON public.prepitch_room_teams TO anon;
GRANT REFERENCES ON public.prepitch_room_teams TO anon;
GRANT SELECT ON public.prepitch_room_teams TO anon;
GRANT TRIGGER ON public.prepitch_room_teams TO anon;
GRANT TRUNCATE ON public.prepitch_room_teams TO anon;
GRANT UPDATE ON public.prepitch_room_teams TO anon;
GRANT DELETE ON public.prepitch_room_teams TO authenticated;
GRANT INSERT ON public.prepitch_room_teams TO authenticated;
GRANT REFERENCES ON public.prepitch_room_teams TO authenticated;
GRANT SELECT ON public.prepitch_room_teams TO authenticated;
GRANT TRIGGER ON public.prepitch_room_teams TO authenticated;
GRANT TRUNCATE ON public.prepitch_room_teams TO authenticated;
GRANT UPDATE ON public.prepitch_room_teams TO authenticated;
GRANT DELETE ON public.prepitch_room_teams TO service_role;
GRANT INSERT ON public.prepitch_room_teams TO service_role;
GRANT REFERENCES ON public.prepitch_room_teams TO service_role;
GRANT SELECT ON public.prepitch_room_teams TO service_role;
GRANT TRIGGER ON public.prepitch_room_teams TO service_role;
GRANT TRUNCATE ON public.prepitch_room_teams TO service_role;
GRANT UPDATE ON public.prepitch_room_teams TO service_role;
GRANT DELETE ON public.prepitch_rooms TO anon;
GRANT INSERT ON public.prepitch_rooms TO anon;
GRANT REFERENCES ON public.prepitch_rooms TO anon;
GRANT SELECT ON public.prepitch_rooms TO anon;
GRANT TRIGGER ON public.prepitch_rooms TO anon;
GRANT TRUNCATE ON public.prepitch_rooms TO anon;
GRANT UPDATE ON public.prepitch_rooms TO anon;
GRANT DELETE ON public.prepitch_rooms TO authenticated;
GRANT INSERT ON public.prepitch_rooms TO authenticated;
GRANT REFERENCES ON public.prepitch_rooms TO authenticated;
GRANT SELECT ON public.prepitch_rooms TO authenticated;
GRANT TRIGGER ON public.prepitch_rooms TO authenticated;
GRANT TRUNCATE ON public.prepitch_rooms TO authenticated;
GRANT UPDATE ON public.prepitch_rooms TO authenticated;
GRANT DELETE ON public.prepitch_rooms TO service_role;
GRANT INSERT ON public.prepitch_rooms TO service_role;
GRANT REFERENCES ON public.prepitch_rooms TO service_role;
GRANT SELECT ON public.prepitch_rooms TO service_role;
GRANT TRIGGER ON public.prepitch_rooms TO service_role;
GRANT TRUNCATE ON public.prepitch_rooms TO service_role;
GRANT UPDATE ON public.prepitch_rooms TO service_role;
GRANT DELETE ON public.push_subscriptions TO anon;
GRANT INSERT ON public.push_subscriptions TO anon;
GRANT REFERENCES ON public.push_subscriptions TO anon;
GRANT SELECT ON public.push_subscriptions TO anon;
GRANT TRIGGER ON public.push_subscriptions TO anon;
GRANT TRUNCATE ON public.push_subscriptions TO anon;
GRANT UPDATE ON public.push_subscriptions TO anon;
GRANT DELETE ON public.push_subscriptions TO authenticated;
GRANT INSERT ON public.push_subscriptions TO authenticated;
GRANT REFERENCES ON public.push_subscriptions TO authenticated;
GRANT SELECT ON public.push_subscriptions TO authenticated;
GRANT TRIGGER ON public.push_subscriptions TO authenticated;
GRANT TRUNCATE ON public.push_subscriptions TO authenticated;
GRANT UPDATE ON public.push_subscriptions TO authenticated;
GRANT DELETE ON public.push_subscriptions TO service_role;
GRANT INSERT ON public.push_subscriptions TO service_role;
GRANT REFERENCES ON public.push_subscriptions TO service_role;
GRANT SELECT ON public.push_subscriptions TO service_role;
GRANT TRIGGER ON public.push_subscriptions TO service_role;
GRANT TRUNCATE ON public.push_subscriptions TO service_role;
GRANT UPDATE ON public.push_subscriptions TO service_role;
GRANT DELETE ON public.rate_limits TO anon;
GRANT INSERT ON public.rate_limits TO anon;
GRANT REFERENCES ON public.rate_limits TO anon;
GRANT SELECT ON public.rate_limits TO anon;
GRANT TRIGGER ON public.rate_limits TO anon;
GRANT TRUNCATE ON public.rate_limits TO anon;
GRANT UPDATE ON public.rate_limits TO anon;
GRANT DELETE ON public.rate_limits TO authenticated;
GRANT INSERT ON public.rate_limits TO authenticated;
GRANT REFERENCES ON public.rate_limits TO authenticated;
GRANT SELECT ON public.rate_limits TO authenticated;
GRANT TRIGGER ON public.rate_limits TO authenticated;
GRANT TRUNCATE ON public.rate_limits TO authenticated;
GRANT UPDATE ON public.rate_limits TO authenticated;
GRANT DELETE ON public.rate_limits TO service_role;
GRANT INSERT ON public.rate_limits TO service_role;
GRANT REFERENCES ON public.rate_limits TO service_role;
GRANT SELECT ON public.rate_limits TO service_role;
GRANT TRIGGER ON public.rate_limits TO service_role;
GRANT TRUNCATE ON public.rate_limits TO service_role;
GRANT UPDATE ON public.rate_limits TO service_role;
GRANT DELETE ON public.registrations TO anon;
GRANT INSERT ON public.registrations TO anon;
GRANT REFERENCES ON public.registrations TO anon;
GRANT SELECT ON public.registrations TO anon;
GRANT TRIGGER ON public.registrations TO anon;
GRANT TRUNCATE ON public.registrations TO anon;
GRANT UPDATE ON public.registrations TO anon;
GRANT DELETE ON public.registrations TO authenticated;
GRANT INSERT ON public.registrations TO authenticated;
GRANT REFERENCES ON public.registrations TO authenticated;
GRANT SELECT ON public.registrations TO authenticated;
GRANT TRIGGER ON public.registrations TO authenticated;
GRANT TRUNCATE ON public.registrations TO authenticated;
GRANT UPDATE ON public.registrations TO authenticated;
GRANT DELETE ON public.registrations TO service_role;
GRANT INSERT ON public.registrations TO service_role;
GRANT REFERENCES ON public.registrations TO service_role;
GRANT SELECT ON public.registrations TO service_role;
GRANT TRIGGER ON public.registrations TO service_role;
GRANT TRUNCATE ON public.registrations TO service_role;
GRANT UPDATE ON public.registrations TO service_role;
GRANT DELETE ON public.resources TO anon;
GRANT INSERT ON public.resources TO anon;
GRANT REFERENCES ON public.resources TO anon;
GRANT SELECT ON public.resources TO anon;
GRANT TRIGGER ON public.resources TO anon;
GRANT TRUNCATE ON public.resources TO anon;
GRANT UPDATE ON public.resources TO anon;
GRANT DELETE ON public.resources TO authenticated;
GRANT INSERT ON public.resources TO authenticated;
GRANT REFERENCES ON public.resources TO authenticated;
GRANT SELECT ON public.resources TO authenticated;
GRANT TRIGGER ON public.resources TO authenticated;
GRANT TRUNCATE ON public.resources TO authenticated;
GRANT UPDATE ON public.resources TO authenticated;
GRANT DELETE ON public.resources TO service_role;
GRANT INSERT ON public.resources TO service_role;
GRANT REFERENCES ON public.resources TO service_role;
GRANT SELECT ON public.resources TO service_role;
GRANT TRIGGER ON public.resources TO service_role;
GRANT TRUNCATE ON public.resources TO service_role;
GRANT UPDATE ON public.resources TO service_role;
GRANT DELETE ON public.schedule_days TO anon;
GRANT INSERT ON public.schedule_days TO anon;
GRANT REFERENCES ON public.schedule_days TO anon;
GRANT SELECT ON public.schedule_days TO anon;
GRANT TRIGGER ON public.schedule_days TO anon;
GRANT TRUNCATE ON public.schedule_days TO anon;
GRANT UPDATE ON public.schedule_days TO anon;
GRANT DELETE ON public.schedule_days TO authenticated;
GRANT INSERT ON public.schedule_days TO authenticated;
GRANT REFERENCES ON public.schedule_days TO authenticated;
GRANT SELECT ON public.schedule_days TO authenticated;
GRANT TRIGGER ON public.schedule_days TO authenticated;
GRANT TRUNCATE ON public.schedule_days TO authenticated;
GRANT UPDATE ON public.schedule_days TO authenticated;
GRANT DELETE ON public.schedule_days TO service_role;
GRANT INSERT ON public.schedule_days TO service_role;
GRANT REFERENCES ON public.schedule_days TO service_role;
GRANT SELECT ON public.schedule_days TO service_role;
GRANT TRIGGER ON public.schedule_days TO service_role;
GRANT TRUNCATE ON public.schedule_days TO service_role;
GRANT UPDATE ON public.schedule_days TO service_role;
GRANT DELETE ON public.schedule_items TO anon;
GRANT INSERT ON public.schedule_items TO anon;
GRANT REFERENCES ON public.schedule_items TO anon;
GRANT SELECT ON public.schedule_items TO anon;
GRANT TRIGGER ON public.schedule_items TO anon;
GRANT TRUNCATE ON public.schedule_items TO anon;
GRANT UPDATE ON public.schedule_items TO anon;
GRANT DELETE ON public.schedule_items TO authenticated;
GRANT INSERT ON public.schedule_items TO authenticated;
GRANT REFERENCES ON public.schedule_items TO authenticated;
GRANT SELECT ON public.schedule_items TO authenticated;
GRANT TRIGGER ON public.schedule_items TO authenticated;
GRANT TRUNCATE ON public.schedule_items TO authenticated;
GRANT UPDATE ON public.schedule_items TO authenticated;
GRANT DELETE ON public.schedule_items TO service_role;
GRANT INSERT ON public.schedule_items TO service_role;
GRANT REFERENCES ON public.schedule_items TO service_role;
GRANT SELECT ON public.schedule_items TO service_role;
GRANT TRIGGER ON public.schedule_items TO service_role;
GRANT TRUNCATE ON public.schedule_items TO service_role;
GRANT UPDATE ON public.schedule_items TO service_role;
GRANT DELETE ON public.slides_config TO anon;
GRANT INSERT ON public.slides_config TO anon;
GRANT REFERENCES ON public.slides_config TO anon;
GRANT SELECT ON public.slides_config TO anon;
GRANT TRIGGER ON public.slides_config TO anon;
GRANT TRUNCATE ON public.slides_config TO anon;
GRANT UPDATE ON public.slides_config TO anon;
GRANT DELETE ON public.slides_config TO authenticated;
GRANT INSERT ON public.slides_config TO authenticated;
GRANT REFERENCES ON public.slides_config TO authenticated;
GRANT SELECT ON public.slides_config TO authenticated;
GRANT TRIGGER ON public.slides_config TO authenticated;
GRANT TRUNCATE ON public.slides_config TO authenticated;
GRANT UPDATE ON public.slides_config TO authenticated;
GRANT DELETE ON public.slides_config TO service_role;
GRANT INSERT ON public.slides_config TO service_role;
GRANT REFERENCES ON public.slides_config TO service_role;
GRANT SELECT ON public.slides_config TO service_role;
GRANT TRIGGER ON public.slides_config TO service_role;
GRANT TRUNCATE ON public.slides_config TO service_role;
GRANT UPDATE ON public.slides_config TO service_role;
GRANT DELETE ON public.sugar_cubes TO anon;
GRANT INSERT ON public.sugar_cubes TO anon;
GRANT REFERENCES ON public.sugar_cubes TO anon;
GRANT SELECT ON public.sugar_cubes TO anon;
GRANT TRIGGER ON public.sugar_cubes TO anon;
GRANT TRUNCATE ON public.sugar_cubes TO anon;
GRANT UPDATE ON public.sugar_cubes TO anon;
GRANT DELETE ON public.sugar_cubes TO authenticated;
GRANT INSERT ON public.sugar_cubes TO authenticated;
GRANT REFERENCES ON public.sugar_cubes TO authenticated;
GRANT SELECT ON public.sugar_cubes TO authenticated;
GRANT TRIGGER ON public.sugar_cubes TO authenticated;
GRANT TRUNCATE ON public.sugar_cubes TO authenticated;
GRANT UPDATE ON public.sugar_cubes TO authenticated;
GRANT DELETE ON public.sugar_cubes TO service_role;
GRANT INSERT ON public.sugar_cubes TO service_role;
GRANT REFERENCES ON public.sugar_cubes TO service_role;
GRANT SELECT ON public.sugar_cubes TO service_role;
GRANT TRIGGER ON public.sugar_cubes TO service_role;
GRANT TRUNCATE ON public.sugar_cubes TO service_role;
GRANT UPDATE ON public.sugar_cubes TO service_role;
GRANT DELETE ON public.team_deliverable_meta TO anon;
GRANT INSERT ON public.team_deliverable_meta TO anon;
GRANT REFERENCES ON public.team_deliverable_meta TO anon;
GRANT SELECT ON public.team_deliverable_meta TO anon;
GRANT TRIGGER ON public.team_deliverable_meta TO anon;
GRANT TRUNCATE ON public.team_deliverable_meta TO anon;
GRANT UPDATE ON public.team_deliverable_meta TO anon;
GRANT DELETE ON public.team_deliverable_meta TO authenticated;
GRANT INSERT ON public.team_deliverable_meta TO authenticated;
GRANT REFERENCES ON public.team_deliverable_meta TO authenticated;
GRANT SELECT ON public.team_deliverable_meta TO authenticated;
GRANT TRIGGER ON public.team_deliverable_meta TO authenticated;
GRANT TRUNCATE ON public.team_deliverable_meta TO authenticated;
GRANT UPDATE ON public.team_deliverable_meta TO authenticated;
GRANT DELETE ON public.team_deliverable_meta TO service_role;
GRANT INSERT ON public.team_deliverable_meta TO service_role;
GRANT REFERENCES ON public.team_deliverable_meta TO service_role;
GRANT SELECT ON public.team_deliverable_meta TO service_role;
GRANT TRIGGER ON public.team_deliverable_meta TO service_role;
GRANT TRUNCATE ON public.team_deliverable_meta TO service_role;
GRANT UPDATE ON public.team_deliverable_meta TO service_role;
GRANT DELETE ON public.team_evaluations TO anon;
GRANT INSERT ON public.team_evaluations TO anon;
GRANT REFERENCES ON public.team_evaluations TO anon;
GRANT SELECT ON public.team_evaluations TO anon;
GRANT TRIGGER ON public.team_evaluations TO anon;
GRANT TRUNCATE ON public.team_evaluations TO anon;
GRANT UPDATE ON public.team_evaluations TO anon;
GRANT DELETE ON public.team_evaluations TO authenticated;
GRANT INSERT ON public.team_evaluations TO authenticated;
GRANT REFERENCES ON public.team_evaluations TO authenticated;
GRANT SELECT ON public.team_evaluations TO authenticated;
GRANT TRIGGER ON public.team_evaluations TO authenticated;
GRANT TRUNCATE ON public.team_evaluations TO authenticated;
GRANT UPDATE ON public.team_evaluations TO authenticated;
GRANT DELETE ON public.team_evaluations TO service_role;
GRANT INSERT ON public.team_evaluations TO service_role;
GRANT REFERENCES ON public.team_evaluations TO service_role;
GRANT SELECT ON public.team_evaluations TO service_role;
GRANT TRIGGER ON public.team_evaluations TO service_role;
GRANT TRUNCATE ON public.team_evaluations TO service_role;
GRANT UPDATE ON public.team_evaluations TO service_role;
GRANT DELETE ON public.team_join_requests TO anon;
GRANT INSERT ON public.team_join_requests TO anon;
GRANT REFERENCES ON public.team_join_requests TO anon;
GRANT SELECT ON public.team_join_requests TO anon;
GRANT TRIGGER ON public.team_join_requests TO anon;
GRANT TRUNCATE ON public.team_join_requests TO anon;
GRANT UPDATE ON public.team_join_requests TO anon;
GRANT DELETE ON public.team_join_requests TO authenticated;
GRANT INSERT ON public.team_join_requests TO authenticated;
GRANT REFERENCES ON public.team_join_requests TO authenticated;
GRANT SELECT ON public.team_join_requests TO authenticated;
GRANT TRIGGER ON public.team_join_requests TO authenticated;
GRANT TRUNCATE ON public.team_join_requests TO authenticated;
GRANT UPDATE ON public.team_join_requests TO authenticated;
GRANT DELETE ON public.team_join_requests TO service_role;
GRANT INSERT ON public.team_join_requests TO service_role;
GRANT REFERENCES ON public.team_join_requests TO service_role;
GRANT SELECT ON public.team_join_requests TO service_role;
GRANT TRIGGER ON public.team_join_requests TO service_role;
GRANT TRUNCATE ON public.team_join_requests TO service_role;
GRANT UPDATE ON public.team_join_requests TO service_role;
GRANT DELETE ON public.teams TO anon;
GRANT INSERT ON public.teams TO anon;
GRANT REFERENCES ON public.teams TO anon;
GRANT SELECT ON public.teams TO anon;
GRANT TRIGGER ON public.teams TO anon;
GRANT TRUNCATE ON public.teams TO anon;
GRANT UPDATE ON public.teams TO anon;
GRANT DELETE ON public.teams TO authenticated;
GRANT INSERT ON public.teams TO authenticated;
GRANT REFERENCES ON public.teams TO authenticated;
GRANT SELECT ON public.teams TO authenticated;
GRANT TRIGGER ON public.teams TO authenticated;
GRANT TRUNCATE ON public.teams TO authenticated;
GRANT UPDATE ON public.teams TO authenticated;
GRANT DELETE ON public.teams TO service_role;
GRANT INSERT ON public.teams TO service_role;
GRANT REFERENCES ON public.teams TO service_role;
GRANT SELECT ON public.teams TO service_role;
GRANT TRIGGER ON public.teams TO service_role;
GRANT TRUNCATE ON public.teams TO service_role;
GRANT UPDATE ON public.teams TO service_role;
GRANT DELETE ON public.waitlist TO anon;
GRANT INSERT ON public.waitlist TO anon;
GRANT REFERENCES ON public.waitlist TO anon;
GRANT SELECT ON public.waitlist TO anon;
GRANT TRIGGER ON public.waitlist TO anon;
GRANT TRUNCATE ON public.waitlist TO anon;
GRANT UPDATE ON public.waitlist TO anon;
GRANT DELETE ON public.waitlist TO authenticated;
GRANT INSERT ON public.waitlist TO authenticated;
GRANT REFERENCES ON public.waitlist TO authenticated;
GRANT SELECT ON public.waitlist TO authenticated;
GRANT TRIGGER ON public.waitlist TO authenticated;
GRANT TRUNCATE ON public.waitlist TO authenticated;
GRANT UPDATE ON public.waitlist TO authenticated;
GRANT DELETE ON public.waitlist TO service_role;
GRANT INSERT ON public.waitlist TO service_role;
GRANT REFERENCES ON public.waitlist TO service_role;
GRANT SELECT ON public.waitlist TO service_role;
GRANT TRIGGER ON public.waitlist TO service_role;
GRANT TRUNCATE ON public.waitlist TO service_role;
GRANT UPDATE ON public.waitlist TO service_role;
GRANT DELETE ON public.wall_state TO anon;
GRANT INSERT ON public.wall_state TO anon;
GRANT REFERENCES ON public.wall_state TO anon;
GRANT SELECT ON public.wall_state TO anon;
GRANT TRIGGER ON public.wall_state TO anon;
GRANT TRUNCATE ON public.wall_state TO anon;
GRANT UPDATE ON public.wall_state TO anon;
GRANT DELETE ON public.wall_state TO authenticated;
GRANT INSERT ON public.wall_state TO authenticated;
GRANT REFERENCES ON public.wall_state TO authenticated;
GRANT SELECT ON public.wall_state TO authenticated;
GRANT TRIGGER ON public.wall_state TO authenticated;
GRANT TRUNCATE ON public.wall_state TO authenticated;
GRANT UPDATE ON public.wall_state TO authenticated;
GRANT DELETE ON public.wall_state TO service_role;
GRANT INSERT ON public.wall_state TO service_role;
GRANT REFERENCES ON public.wall_state TO service_role;
GRANT SELECT ON public.wall_state TO service_role;
GRANT TRIGGER ON public.wall_state TO service_role;
GRANT TRUNCATE ON public.wall_state TO service_role;
GRANT UPDATE ON public.wall_state TO service_role;
REVOKE ALL ON FUNCTION public.admin_create_grant(p_label text, p_role text, p_scope jsonb, p_expires_at timestamp with time zone, p_email text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_list_grants() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_list_jurors() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_list_mentors() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_notifications_history(p_limit integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_regenerate_grant_token(p_grant_id uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_revoke_grant(p_grant_id uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_set_grant_expiry(p_grant_id uuid, p_expires_at timestamp with time zone) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_teams_for_broadcast() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.assert_tab(VARIADIC p_tabs text[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.broadcast_notification(p_title text, p_body text, p_audience_kind text, p_team_ids uuid[], p_url text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.can_write() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.clear_announcement() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.current_grant_ref() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.current_juror_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.current_mentor_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.event_eval_resolve(p_token uuid, p_type text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.expand_recipients(p_notification_id uuid, p_audience jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_app_setting(p_key text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_event_evaluation_results() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_juror_idea_visible() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_mp_fee_summary() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_notify_events() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_sugar_released() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_team_scores_visible() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.grant_resolve(p_token text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.grant_resolve_internal(p_token text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_checkin_staff() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_facilitator() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_wall_staff() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.juror_force_reload() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.my_scope() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notifications_list_admin(p_limit integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notifications_list_mentor(p_token text, p_limit integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notifications_list_participant(p_token text, p_limit integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notifications_mark_read_admin(p_ids uuid[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notifications_mark_read_mentor(p_token text, p_ids uuid[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notifications_mark_read_participant(p_token text, p_ids uuid[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notify_event(p_event_key text, p_title text, p_body text, p_url text, p_audience jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notify_schedule_start(p_item_id uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.push_subscribe_admin(p_endpoint text, p_p256dh text, p_auth text, p_ua text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.push_subscribe_mentor(p_token text, p_endpoint text, p_p256dh text, p_auth text, p_ua text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.push_subscribe_participant(p_token text, p_endpoint text, p_p256dh text, p_auth text, p_ua text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.push_unsubscribe(p_endpoint text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.scope_read_only() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.scope_tab_allowed(p_tab text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_announcement(p_body text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_checkin(p_id uuid, p_present boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_evaluation_open(p_open boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_juror_idea_visible(p_visible boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_notify_event(p_event_key text, p_on boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_slides_deadline(p_deadline timestamp with time zone) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_sugar_released(p_bool boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_team_lunch(p_team_id uuid, p_done boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_team_scores_visible(p_visible boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.slides_upload_allowed() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sugar_admin_list(p_status text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sugar_insert(p_sender_type text, p_sender_ref uuid, p_sender_name text, p_recipient_type text, p_recipient_ref uuid, p_message text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sugar_moderate(p_id uuid, p_status text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sugar_resolve_recipient(p_type text, p_ref uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sugar_roster_admin() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sugar_send_org(p_recipient_type text, p_recipient_ref uuid, p_message text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sugar_send_participant(p_token uuid, p_recipient_type text, p_recipient_ref uuid, p_message text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.wall_admin_add_pain(p_registration_id uuid, p_title text, p_description text, p_axis text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.wall_admin_list() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.wall_display_name(p_full_name text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.wall_get_phase() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.wall_hide_pain(p_id uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.wall_require_confirmed(p_registration_id uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.wall_resolve_token(p_token uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.wall_set_phase(p_phase text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.wall_unhide_pain(p_id uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_cancel_bulk_order(p_order_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_cancel_bulk_order(p_order_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_cancel_bulk_order(p_order_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_cancel_voucher(p_voucher_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_cancel_voucher(p_voucher_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_cancel_voucher(p_voucher_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_confirm_bulk_order(p_order_id uuid, p_payment_method text, p_payment_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_confirm_bulk_order(p_order_id uuid, p_payment_method text, p_payment_notes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_confirm_bulk_order(p_order_id uuid, p_payment_method text, p_payment_notes text) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_create_bulk_order(p_company_name text, p_cnpj text, p_contact_name text, p_contact_email text, p_contact_phone text, p_total_tickets integer, p_ticket_price integer, p_ticket_tier text, p_payment_method text, p_payment_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_create_bulk_order(p_company_name text, p_cnpj text, p_contact_name text, p_contact_email text, p_contact_phone text, p_total_tickets integer, p_ticket_price integer, p_ticket_tier text, p_payment_method text, p_payment_notes text) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_create_bulk_order(p_company_name text, p_cnpj text, p_contact_name text, p_contact_email text, p_contact_phone text, p_total_tickets integer, p_ticket_price integer, p_ticket_tier text, p_payment_method text, p_payment_notes text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_grant(p_label text, p_role text, p_scope jsonb, p_expires_at timestamp with time zone, p_email text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_grant(p_label text, p_role text, p_scope jsonb, p_expires_at timestamp with time zone, p_email text) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_create_grant(p_label text, p_role text, p_scope jsonb, p_expires_at timestamp with time zone, p_email text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_create_mentor(p_email text, p_name text) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_create_mentor(p_email text, p_name text) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_create_mentor(p_email text, p_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_bulk_order(p_order_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_get_bulk_order(p_order_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_get_bulk_order(p_order_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_bulk_orders() TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_list_bulk_orders() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_bulk_orders() TO anon;
GRANT EXECUTE ON FUNCTION public.admin_list_grants() TO anon;
GRANT EXECUTE ON FUNCTION public.admin_list_grants() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_grants() TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_list_jurors() TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_list_jurors() TO anon;
GRANT EXECUTE ON FUNCTION public.admin_list_jurors() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_mentors() TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_list_mentors() TO anon;
GRANT EXECUTE ON FUNCTION public.admin_list_mentors() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_notifications_history(p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_notifications_history(p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_promote_leader(p_team_name text, p_new_leader_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_promote_leader(p_team_name text, p_new_leader_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_promote_leader(p_team_name text, p_new_leader_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_regenerate_grant_token(p_grant_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_regenerate_grant_token(p_grant_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_regenerate_grant_token(p_grant_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_reset_mentor_code(p_mentor_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_reset_mentor_code(p_mentor_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_reset_mentor_code(p_mentor_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_revoke_grant(p_grant_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_revoke_grant(p_grant_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_revoke_grant(p_grant_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_grant_expiry(p_grant_id uuid, p_expires_at timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_grant_expiry(p_grant_id uuid, p_expires_at timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_grant_expiry(p_grant_id uuid, p_expires_at timestamp with time zone) TO anon;
GRANT EXECUTE ON FUNCTION public.admin_teams_for_broadcast() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_teams_for_broadcast() TO service_role;
GRANT EXECUTE ON FUNCTION public.anonymize_user_data(p_email text) TO anon;
GRANT EXECUTE ON FUNCTION public.anonymize_user_data(p_email text) TO service_role;
GRANT EXECUTE ON FUNCTION public.anonymize_user_data(p_email text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assert_tab(VARIADIC p_tabs text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.assert_tab(VARIADIC p_tabs text[]) TO anon;
GRANT EXECUTE ON FUNCTION public.assert_tab(VARIADIC p_tabs text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.broadcast_notification(p_title text, p_body text, p_audience_kind text, p_team_ids uuid[], p_url text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.broadcast_notification(p_title text, p_body text, p_audience_kind text, p_team_ids uuid[], p_url text) TO service_role;
GRANT EXECUTE ON FUNCTION public.can_write() TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_write() TO service_role;
GRANT EXECUTE ON FUNCTION public.can_write() TO anon;
GRANT EXECUTE ON FUNCTION public.cascade_team_rename() TO service_role;
GRANT EXECUTE ON FUNCTION public.cascade_team_rename() TO anon;
GRANT EXECUTE ON FUNCTION public.cascade_team_rename() TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_rate_limit(p_key text, p_max_attempts integer, p_window_minutes integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_rate_limit(p_key text, p_max_attempts integer, p_window_minutes integer) TO anon;
GRANT EXECUTE ON FUNCTION public.check_rate_limit(p_key text, p_max_attempts integer, p_window_minutes integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_team_size() TO anon;
GRANT EXECUTE ON FUNCTION public.check_team_size() TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_team_size() TO service_role;
GRANT EXECUTE ON FUNCTION public.check_team_size_update() TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_team_size_update() TO service_role;
GRANT EXECUTE ON FUNCTION public.check_team_size_update() TO anon;
GRANT EXECUTE ON FUNCTION public.claim_early_bird_slot(p_reg_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.claim_early_bird_slot(p_reg_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.clear_announcement() TO authenticated;
GRANT EXECUTE ON FUNCTION public.clear_announcement() TO service_role;
GRANT EXECUTE ON FUNCTION public.current_grant_ref() TO service_role;
GRANT EXECUTE ON FUNCTION public.current_grant_ref() TO anon;
GRANT EXECUTE ON FUNCTION public.current_grant_ref() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_juror_id() TO service_role;
GRANT EXECUTE ON FUNCTION public.current_juror_id() TO anon;
GRANT EXECUTE ON FUNCTION public.current_juror_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_mentor_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_mentor_id() TO service_role;
GRANT EXECUTE ON FUNCTION public.current_mentor_id() TO anon;
GRANT EXECUTE ON FUNCTION public.enforce_anon_insert_defaults() TO service_role;
GRANT EXECUTE ON FUNCTION public.enforce_anon_insert_defaults() TO authenticated;
GRANT EXECUTE ON FUNCTION public.enforce_anon_insert_defaults() TO anon;
GRANT EXECUTE ON FUNCTION public.enforce_ticket_price() TO service_role;
GRANT EXECUTE ON FUNCTION public.enforce_ticket_price() TO authenticated;
GRANT EXECUTE ON FUNCTION public.enforce_ticket_price() TO anon;
GRANT EXECUTE ON FUNCTION public.event_eval_resolve(p_token uuid, p_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.event_eval_resolve(p_token uuid, p_type text) TO service_role;
GRANT EXECUTE ON FUNCTION public.event_eval_resolve(p_token uuid, p_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.expand_recipients(p_notification_id uuid, p_audience jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.expand_recipients(p_notification_id uuid, p_audience jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_voucher_code() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_voucher_code() TO anon;
GRANT EXECUTE ON FUNCTION public.generate_voucher_code() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_active_announcement() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_active_announcement() TO anon;
GRANT EXECUTE ON FUNCTION public.get_active_announcement() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_app_setting(p_key text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_confirmed_count() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_confirmed_count() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_confirmed_count() TO anon;
GRANT EXECUTE ON FUNCTION public.get_early_bird_sold() TO anon;
GRANT EXECUTE ON FUNCTION public.get_early_bird_sold() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_early_bird_sold() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_event_evaluation_results() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_event_evaluation_results() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_juror_idea_visible() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_juror_idea_visible() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_mp_fee_summary() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_mp_fee_summary() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_my_event_evaluation(p_token uuid, p_type text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_my_event_evaluation(p_token uuid, p_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_event_evaluation(p_token uuid, p_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_notify_events() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_notify_events() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_public_schedule() TO anon;
GRANT EXECUTE ON FUNCTION public.get_public_schedule() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_public_schedule() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_slides_deadline() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_slides_deadline() TO anon;
GRANT EXECUTE ON FUNCTION public.get_slides_deadline() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_sugar_released() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_sugar_released() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_team_phase_aliases() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_team_phase_aliases() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_team_phase_aliases() TO anon;
GRANT EXECUTE ON FUNCTION public.get_team_scores_visible() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_team_scores_visible() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_total_registration_count() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_total_registration_count() TO anon;
GRANT EXECUTE ON FUNCTION public.get_total_registration_count() TO service_role;
GRANT EXECUTE ON FUNCTION public.grant_auth_kind(p_role text) TO anon;
GRANT EXECUTE ON FUNCTION public.grant_auth_kind(p_role text) TO service_role;
GRANT EXECUTE ON FUNCTION public.grant_auth_kind(p_role text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_resolve(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.grant_resolve(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.grant_resolve(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_resolve_internal(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.grant_resolve_internal(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.grant_resolve_internal(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO service_role;
GRANT EXECUTE ON FUNCTION public.is_admin() TO anon;
GRANT EXECUTE ON FUNCTION public.is_admin_or_viewer() TO service_role;
GRANT EXECUTE ON FUNCTION public.is_admin_or_viewer() TO anon;
GRANT EXECUTE ON FUNCTION public.is_admin_or_viewer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_checkin_staff() TO service_role;
GRANT EXECUTE ON FUNCTION public.is_checkin_staff() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_facilitator() TO service_role;
GRANT EXECUTE ON FUNCTION public.is_facilitator() TO anon;
GRANT EXECUTE ON FUNCTION public.is_facilitator() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_wall_staff() TO service_role;
GRANT EXECUTE ON FUNCTION public.is_wall_staff() TO authenticated;
GRANT EXECUTE ON FUNCTION public.juror_accept_consent(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.juror_accept_consent(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.juror_accept_consent(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.juror_force_reload() TO authenticated;
GRANT EXECUTE ON FUNCTION public.juror_force_reload() TO service_role;
GRANT EXECUTE ON FUNCTION public.juror_get_context(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.juror_get_context(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.juror_get_context(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.juror_submit_score(p_token text, p_team_id uuid, p_scores jsonb, p_summary text, p_eliminated boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.juror_submit_score(p_token text, p_team_id uuid, p_scores jsonb, p_summary text, p_eliminated boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.juror_submit_score(p_token text, p_team_id uuid, p_scores jsonb, p_summary text, p_eliminated boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.juror_token_owner(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.juror_token_owner(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.juror_token_owner(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.lookup_voucher(p_code text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.lookup_voucher(p_code text) TO service_role;
GRANT EXECUTE ON FUNCTION public.lookup_voucher(p_code text) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_delete_note(p_token text, p_note_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.mentor_delete_note(p_token text, p_note_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_delete_note(p_token text, p_note_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_get_me(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_get_me(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_get_me(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mentor_get_me_by_token(p_access_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_get_me_by_token(p_access_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mentor_get_me_by_token(p_access_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_login(p_email text, p_code text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mentor_login(p_email text, p_code text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_login(p_email text, p_code text) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_logout(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_logout(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_logout(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mentor_prepitch_list(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_prepitch_list(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_prepitch_list(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mentor_prepitch_resolve(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_prepitch_resolve(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_prepitch_resolve(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mentor_prepitch_submit(p_token text, p_team_id uuid, p_round integer, p_scores jsonb, p_summary text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_prepitch_submit(p_token text, p_team_id uuid, p_round integer, p_scores jsonb, p_summary text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mentor_prepitch_submit(p_token text, p_team_id uuid, p_round integer, p_scores jsonb, p_summary text) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_save_note(p_token text, p_phase text, p_body text, p_is_public boolean, p_note_id uuid, p_team_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.mentor_save_note(p_token text, p_phase text, p_body text, p_is_public boolean, p_note_id uuid, p_team_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_save_note(p_token text, p_phase text, p_body text, p_is_public boolean, p_note_id uuid, p_team_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_serialize_me(p_mentor_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.mentor_serialize_me(p_mentor_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_serialize_me(p_mentor_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_session_owner(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.mentor_session_owner(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mentor_session_owner(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.my_scope() TO service_role;
GRANT EXECUTE ON FUNCTION public.my_scope() TO authenticated;
GRANT EXECUTE ON FUNCTION public.my_scope() TO anon;
GRANT EXECUTE ON FUNCTION public.notifications_list_admin(p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.notifications_list_admin(p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.notifications_list_mentor(p_token text, p_limit integer) TO anon;
GRANT EXECUTE ON FUNCTION public.notifications_list_mentor(p_token text, p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.notifications_list_mentor(p_token text, p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.notifications_list_participant(p_token text, p_limit integer) TO anon;
GRANT EXECUTE ON FUNCTION public.notifications_list_participant(p_token text, p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.notifications_list_participant(p_token text, p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.notifications_mark_read_admin(p_ids uuid[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.notifications_mark_read_admin(p_ids uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.notifications_mark_read_mentor(p_token text, p_ids uuid[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.notifications_mark_read_mentor(p_token text, p_ids uuid[]) TO anon;
GRANT EXECUTE ON FUNCTION public.notifications_mark_read_mentor(p_token text, p_ids uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.notifications_mark_read_participant(p_token text, p_ids uuid[]) TO anon;
GRANT EXECUTE ON FUNCTION public.notifications_mark_read_participant(p_token text, p_ids uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.notifications_mark_read_participant(p_token text, p_ids uuid[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.notify_event(p_event_key text, p_title text, p_body text, p_url text, p_audience jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.notify_event(p_event_key text, p_title text, p_body text, p_url text, p_audience jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.notify_schedule_start(p_item_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.notify_schedule_start(p_item_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_approve_request(p_token uuid, p_request_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_approve_request(p_token uuid, p_request_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_approve_request(p_token uuid, p_request_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_cancel_request(p_token uuid, p_request_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_cancel_request(p_token uuid, p_request_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_cancel_request(p_token uuid, p_request_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_create_team(p_token uuid, p_team_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_create_team(p_token uuid, p_team_name text) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_create_team(p_token uuid, p_team_name text) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_get_me(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_get_me(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_get_me(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_get_team_scores(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_get_team_scores(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_get_team_scores(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_leave_team(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_leave_team(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_leave_team(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_list_resources(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_list_resources(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_list_resources(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_list_teams(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_list_teams(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_list_teams(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_login(p_email text, p_cpf text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_login(p_email text, p_cpf text) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_login(p_email text, p_cpf text) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_logout(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_logout(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_logout(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_prepitch_feedback(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_prepitch_feedback(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_prepitch_feedback(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_reject_request(p_token uuid, p_request_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_reject_request(p_token uuid, p_request_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_reject_request(p_token uuid, p_request_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_request_join(p_token uuid, p_team_name text, p_message text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_request_join(p_token uuid, p_team_name text, p_message text) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_request_join(p_token uuid, p_team_name text, p_message text) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_save_team_deliverable(p_token uuid, p_field text, p_data jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_save_team_deliverable(p_token uuid, p_field text, p_data jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_save_team_deliverable(p_token uuid, p_field text, p_data jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_session_owner(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_session_owner(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_session_owner(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_session_owner_confirmed(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_session_owner_confirmed(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_session_owner_confirmed(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_transfer_leadership(p_token uuid, p_new_leader_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_transfer_leadership(p_token uuid, p_new_leader_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_transfer_leadership(p_token uuid, p_new_leader_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_update_profile(p_token uuid, p_phone text, p_linkedin_url text, p_dietary_restrictions text, p_is_pcd boolean, p_pcd_type text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_update_profile(p_token uuid, p_phone text, p_linkedin_url text, p_dietary_restrictions text, p_is_pcd boolean, p_pcd_type text) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_update_profile(p_token uuid, p_phone text, p_linkedin_url text, p_dietary_restrictions text, p_is_pcd boolean, p_pcd_type text) TO service_role;
GRANT EXECUTE ON FUNCTION public.participant_update_team(p_token uuid, p_team_name text, p_idea_description text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.participant_update_team(p_token uuid, p_team_name text, p_idea_description text) TO anon;
GRANT EXECUTE ON FUNCTION public.participant_update_team(p_token uuid, p_team_name text, p_idea_description text) TO service_role;
GRANT EXECUTE ON FUNCTION public.public_list_teams() TO anon;
GRANT EXECUTE ON FUNCTION public.public_list_teams() TO service_role;
GRANT EXECUTE ON FUNCTION public.public_list_teams() TO authenticated;
GRANT EXECUTE ON FUNCTION public.push_subscribe_admin(p_endpoint text, p_p256dh text, p_auth text, p_ua text) TO service_role;
GRANT EXECUTE ON FUNCTION public.push_subscribe_admin(p_endpoint text, p_p256dh text, p_auth text, p_ua text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.push_subscribe_admin(p_endpoint text, p_p256dh text, p_auth text, p_ua text) TO anon;
GRANT EXECUTE ON FUNCTION public.push_subscribe_mentor(p_token text, p_endpoint text, p_p256dh text, p_auth text, p_ua text) TO anon;
GRANT EXECUTE ON FUNCTION public.push_subscribe_mentor(p_token text, p_endpoint text, p_p256dh text, p_auth text, p_ua text) TO service_role;
GRANT EXECUTE ON FUNCTION public.push_subscribe_mentor(p_token text, p_endpoint text, p_p256dh text, p_auth text, p_ua text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.push_subscribe_participant(p_token text, p_endpoint text, p_p256dh text, p_auth text, p_ua text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.push_subscribe_participant(p_token text, p_endpoint text, p_p256dh text, p_auth text, p_ua text) TO service_role;
GRANT EXECUTE ON FUNCTION public.push_subscribe_participant(p_token text, p_endpoint text, p_p256dh text, p_auth text, p_ua text) TO anon;
GRANT EXECUTE ON FUNCTION public.push_unsubscribe(p_endpoint text) TO service_role;
GRANT EXECUTE ON FUNCTION public.push_unsubscribe(p_endpoint text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.push_unsubscribe(p_endpoint text) TO anon;
GRANT EXECUTE ON FUNCTION public.recover_pending_registration(p_email text) TO anon;
GRANT EXECUTE ON FUNCTION public.recover_pending_registration(p_email text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.recover_pending_registration(p_email text) TO service_role;
GRANT EXECUTE ON FUNCTION public.redeem_voucher(p_code text, p_data jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.redeem_voucher(p_code text, p_data jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.redeem_voucher(p_code text, p_data jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.scope_read_only() TO authenticated;
GRANT EXECUTE ON FUNCTION public.scope_read_only() TO service_role;
GRANT EXECUTE ON FUNCTION public.scope_read_only() TO anon;
GRANT EXECUTE ON FUNCTION public.scope_tab_allowed(p_tab text) TO anon;
GRANT EXECUTE ON FUNCTION public.scope_tab_allowed(p_tab text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.scope_tab_allowed(p_tab text) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_announcement(p_body text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_announcement(p_body text) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_checkin(p_id uuid, p_present boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_checkin(p_id uuid, p_present boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_evaluation_open(p_open boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_evaluation_open(p_open boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_juror_idea_visible(p_visible boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_juror_idea_visible(p_visible boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_notify_event(p_event_key text, p_on boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_notify_event(p_event_key text, p_on boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_slides_deadline(p_deadline timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_slides_deadline(p_deadline timestamp with time zone) TO anon;
GRANT EXECUTE ON FUNCTION public.set_slides_deadline(p_deadline timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_sugar_released(p_bool boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_sugar_released(p_bool boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_team_lunch(p_team_id uuid, p_done boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_team_lunch(p_team_id uuid, p_done boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_team_phase_aliases(p_aliases jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_team_phase_aliases(p_aliases jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_team_phase_aliases(p_aliases jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.set_team_scores_visible(p_visible boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_team_scores_visible(p_visible boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.slides_upload_allowed() TO anon;
GRANT EXECUTE ON FUNCTION public.slides_upload_allowed() TO authenticated;
GRANT EXECUTE ON FUNCTION public.slides_upload_allowed() TO service_role;
GRANT EXECUTE ON FUNCTION public.submit_event_evaluation(p_token uuid, p_type text, p_scores jsonb, p_comment text) TO service_role;
GRANT EXECUTE ON FUNCTION public.submit_event_evaluation(p_token uuid, p_type text, p_scores jsonb, p_comment text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_event_evaluation(p_token uuid, p_type text, p_scores jsonb, p_comment text) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_admin_list(p_status text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sugar_admin_list(p_status text) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_admin_list(p_status text) TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_insert(p_sender_type text, p_sender_ref uuid, p_sender_name text, p_recipient_type text, p_recipient_ref uuid, p_message text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sugar_insert(p_sender_type text, p_sender_ref uuid, p_sender_name text, p_recipient_type text, p_recipient_ref uuid, p_message text) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_insert(p_sender_type text, p_sender_ref uuid, p_sender_name text, p_recipient_type text, p_recipient_ref uuid, p_message text) TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_moderate(p_id uuid, p_status text) TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_moderate(p_id uuid, p_status text) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_moderate(p_id uuid, p_status text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sugar_my_received_mentor(p_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_my_received_mentor(p_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_my_received_mentor(p_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sugar_my_received_participant(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_my_received_participant(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sugar_my_received_participant(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_resolve_recipient(p_type text, p_ref uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_resolve_recipient(p_type text, p_ref uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sugar_resolve_recipient(p_type text, p_ref uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_roster(p_participant_token uuid, p_mentor_token text) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_roster(p_participant_token uuid, p_mentor_token text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sugar_roster(p_participant_token uuid, p_mentor_token text) TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_roster_admin() TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_roster_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sugar_roster_admin() TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_send_mentor(p_token text, p_recipient_type text, p_recipient_ref uuid, p_message text) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_send_mentor(p_token text, p_recipient_type text, p_recipient_ref uuid, p_message text) TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_send_mentor(p_token text, p_recipient_type text, p_recipient_ref uuid, p_message text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sugar_send_org(p_recipient_type text, p_recipient_ref uuid, p_message text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sugar_send_org(p_recipient_type text, p_recipient_ref uuid, p_message text) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_send_org(p_recipient_type text, p_recipient_ref uuid, p_message text) TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_send_participant(p_token uuid, p_recipient_type text, p_recipient_ref uuid, p_message text) TO service_role;
GRANT EXECUTE ON FUNCTION public.sugar_send_participant(p_token uuid, p_recipient_type text, p_recipient_ref uuid, p_message text) TO anon;
GRANT EXECUTE ON FUNCTION public.sugar_send_participant(p_token uuid, p_recipient_type text, p_recipient_ref uuid, p_message text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sync_registration_team_id() TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_registration_team_id() TO anon;
GRANT EXECUTE ON FUNCTION public.sync_registration_team_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.transfer_ticket(p_from_id uuid, p_to_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.transfer_ticket(p_from_id uuid, p_to_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.transfer_ticket(p_from_id uuid, p_to_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.trg_notifications_send_push() TO authenticated;
GRANT EXECUTE ON FUNCTION public.trg_notifications_send_push() TO anon;
GRANT EXECUTE ON FUNCTION public.trg_notifications_send_push() TO service_role;
GRANT EXECUTE ON FUNCTION public.trg_notify_mentor_assigned() TO anon;
GRANT EXECUTE ON FUNCTION public.trg_notify_mentor_assigned() TO authenticated;
GRANT EXECUTE ON FUNCTION public.trg_notify_mentor_assigned() TO service_role;
GRANT EXECUTE ON FUNCTION public.trg_notify_payment_confirmed() TO anon;
GRANT EXECUTE ON FUNCTION public.trg_notify_payment_confirmed() TO service_role;
GRANT EXECUTE ON FUNCTION public.trg_notify_payment_confirmed() TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_admin_add_pain(p_registration_id uuid, p_title text, p_description text, p_axis text) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_admin_add_pain(p_registration_id uuid, p_title text, p_description text, p_axis text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_admin_add_pain(p_registration_id uuid, p_title text, p_description text, p_axis text) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_admin_list() TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_admin_list() TO anon;
GRANT EXECUTE ON FUNCTION public.wall_admin_list() TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_display_name(p_full_name text) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_display_name(p_full_name text) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_display_name(p_full_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_get_phase() TO anon;
GRANT EXECUTE ON FUNCTION public.wall_get_phase() TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_get_phase() TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_hide_pain(p_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_hide_pain(p_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_hide_pain(p_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_identify(p_cpf text, p_birth_date date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_identify(p_cpf text, p_birth_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_identify(p_cpf text, p_birth_date date) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_list(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_list(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_list(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_require_confirmed(p_registration_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_require_confirmed(p_registration_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_resolve_token(p_token uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_resolve_token(p_token uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_resolve_token(p_token uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_set_phase(p_phase text) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_set_phase(p_phase text) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_set_phase(p_phase text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_submit_pain(p_token uuid, p_title text, p_description text, p_axis text) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_submit_pain(p_token uuid, p_title text, p_description text, p_axis text) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_submit_pain(p_token uuid, p_title text, p_description text, p_axis text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_unhide_pain(p_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_unhide_pain(p_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_unhide_pain(p_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_unvote(p_token uuid, p_pain_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_unvote(p_token uuid, p_pain_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_unvote(p_token uuid, p_pain_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.wall_vote(p_token uuid, p_pain_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.wall_vote(p_token uuid, p_pain_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.wall_vote(p_token uuid, p_pain_id uuid) TO service_role;
